terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
    }
  }
}

# google provider block with only region set to europe north1
provider "google" {
}

# create a CaPool resource. Located in europe west 4, enterprise tier and set publishing options ca cert and crl to true.
resource "google_ca_certificate" "name_0" {
  provider = google-beta
  name    = "my-ca-certificate"
  type    = "CNAME"
  certificate = file("${path.module}/ca.pem")

  # IMPORTANT: this file MUST be generated by hand! Do not edit it!
  lifecycle {
    create_before_destroy = true
  }
}

