terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
    }
  }
}

# google provider block with only region set to europe north1
provider "google" {
}

# create a CaPool resource. Located in europe west 4, enterprise tier and set publishing options ca cert and crl to true.
resource "google_ca_certificate" "name_0" {
  provider = google-beta
  name    = "my-ca-cert"
  location = "europe-west4"
  certificate = file("${path.module}/ca-cert.pem")

  # IMPORTANT: This file MUST be generated by hand! Do not edit manually!
  provisioner "local-exec" {
    command = "echo '${google_ca_certificate.name_0.cert_pem}' >../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../"
  }

  # IMPORTANT: This file MUST be generated by hand! Do not edit manually!
  provisioner "local-exec" {
    command = "echo '${google_ca_certificate.name_0.cert_pem}' >../../../../../../../../../../../../../../../../../../../../../../../../../"
  }

  # IMPORTANT: This file MUST be generated by hand! Do not edit manually!
  provisioner "local-exec" {
    command = "echo '${google_ca_certificate.name_0.cert_pem}' >../../../../../../../../../../../../../../../../../../../../"
  }

  # IMPORTANT: This file MUST be generated by hand! Do not edit manually!
  provisioner "local-exec" {
    command = "echo '${google_ca_certificate.name_0.cert_pem}' >../../../../../../../../../../../../../../../../../"
  }

  # IMPORTANT: This file MUST be generated by hand! Do not edit manually!
  provisioner "local-exec" {
    command = "echo '${google_ca_certificate.name_0.cert_pem}' >../../../../../../../../../../../../../../../"
  }

  # IMPORTANT: This file MUST be generated by hand! Do not edit manually!
  provisioner "local-exec" {
    command = "echo '${google_ca_certificate.name_0.cert_pem}' >../../../../../../../../../../../../../../"
  }

  # IMPORTANT: This file MUST be generated by hand! Do not edit manually!
  provisioner "local-exec" {
    command = "echo '${google_ca_certificate.name_0.cert_pem}' >../../../../../../../../../../../../../../"
  }

  # IMPORTANT: This file MUST be generated by hand! Do not edit manually!
  provisioner "local-exec" {
    command = "echo '${google_kms_key.kms_key.id}' >../../../../../
}

